# Generated by Django 5.2.11 on 2026-03-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_trigger',
            field=models.ImageField(blank=True, null=True, upload_to='products/temp/'),
        ),
    ]
