# Generated by Django 5.2.11 on 2026-03-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_thumbnail_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_trigger',
        ),
    ]
