# Generated by Django 5.2.11 on 2026-02-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_size_remove_product_is_featured_lehenga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='Separate instructions by new lines (Optional)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Separate features by new lines (Optional)', null=True),
        ),
    ]
