# Generated by Django 5.2.11 on 2026-02-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_care_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price_override',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra amount to add to base prices (e.g., 200 for L size)', max_digits=10),
        ),
    ]
