# Generated by Django 5.2.11 on 2026-02-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productvariant_price_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
