# Generated by Django 5.2.11 on 2026-02-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_subcategory_delete_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured_lehenga',
            field=models.BooleanField(default=False, verbose_name='In Featured Lehengas'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_kids_collection',
            field=models.BooleanField(default=False, verbose_name='In Kids Collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_saree_collection',
            field=models.BooleanField(default=False, verbose_name='In Sarees Collection'),
        ),
    ]
