# Generated by Django 5.2.11 on 2026-02-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_is_featured_lehenga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchAndBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/watch_buy/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_videos', to='store.product')),
            ],
            options={
                'verbose_name': 'Watch & Buy Video',
                'verbose_name_plural': 'Watch & Buy Videos',
            },
        ),
    ]
