# Generated by Django 5.2.11 on 2026-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_watchandbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_watch_and_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/products/'),
        ),
        migrations.DeleteModel(
            name='WatchAndBuy',
        ),
    ]
