# Generated by Django 5.2.11 on 2026-02-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_is_watch_and_buy_productimage_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=100)),
                ('uses_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Miscellaneous Charges', 'verbose_name_plural': 'Miscellaneous Charges'},
        ),
    ]
