# Generated by Django 5.2.11 on 2026-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_coupon_alter_siteconfig_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Toggle to show on Homepage Testimonials'),
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
