# Generated by Django 5.2.11 on 2026-03-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_review_is_featured_review_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_kids_collection',
        ),
    ]
