# Generated by Django 5.2.11 on 2026-03-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_is_kids_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_watch_and_buy',
        ),
    ]
