# Generated by Django 5.2.11 on 2026-02-15 12:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchAndBuyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('video_file', models.FileField(upload_to='watch_buy_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'mkv'])])),
                ('thumbnail', models.ImageField(blank=True, upload_to='watch_buy_thumbnails/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('care_instructions', models.TextField(blank=True)),
                ('features', models.JSONField(default=list, help_text="Example: ['Hand-stitched', 'Silk Fabric']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('video_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='watch_and_buy.watchandbuyvideo')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='watch_and_buy.watchandbuyvideo')),
            ],
        ),
    ]
