# Generated by Django 5.2.11 on 2026-03-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_and_buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchandbuyvideo',
            name='thumbnail',
            field=models.ImageField(upload_to='watch_buy_thumbnails/'),
        ),
    ]
