# Generated by Django 5.2.11 on 2026-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_and_buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videovariant',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='videovariant',
            name='color_note',
            field=models.CharField(blank=True, help_text="e.g., 'The 5th saree shown in the video'", max_length=255),
        ),
        migrations.AlterField(
            model_name='videovariant',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='watchandbuyvideo',
            name='care_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchandbuyvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchandbuyvideo',
            name='features',
            field=models.TextField(blank=True, help_text='Enter features separated by commas', null=True),
        ),
    ]
