# Generated by Django 5.2.11 on 2026-02-15 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_and_buy', '0002_videovariant_color_videovariant_color_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproductreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watch_buy_reviews/'),
        ),
        migrations.AddField(
            model_name='videoproductreview',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videoproductreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
