# Generated by Django 5.2.11 on 2026-02-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon_image', models.ImageField(help_text='Upload a white/transparent PNG icon', upload_to='features/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BrandStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Story', max_length=100)),
                ('content', models.TextField(help_text='The main paragraph text')),
                ('image_1', models.ImageField(upload_to='story/')),
                ('image_2', models.ImageField(upload_to='story/')),
            ],
            options={
                'verbose_name_plural': 'Brand Story',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('button_text', models.CharField(default='SHOP NOW', max_length=50)),
                ('button_link', models.CharField(default='/products', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order of appearance')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
