# Generated by Django 5.2.11 on 2026-03-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Text for the top scrolling bar', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BrandStorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='The Art of Draping', max_length=100)),
                ('heading', models.CharField(default='Traditional Elegance | Effortlessly Styled', help_text="Line 1 and Line 2 are separated by '|'. Line 2 will automatically be Pink and Italic.", max_length=255)),
                ('content', models.TextField(default='Every design is a tribute to the timeless beauty of the Indian woman.', help_text='The main description (rendered in italics)')),
                ('experience_years', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended Ratios: 21:8 for Desktop (e.g., 2100x800px) and 3:2 for Mobile (e.g., 1200x800px). Ensure titles are part of the image.', upload_to='hero_slides/')),
                ('link_url', models.CharField(default='/category/all', help_text='The internal route the user goes to (e.g., /category/sarees or /category/all)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BrandStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand_story/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.brandstorysettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
