# Generated by Django 5.2.11 on 2026-02-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Text for the top scrolling bar', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BrandStorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='The Essence of GTD', max_length=100)),
                ('heading', models.CharField(default='Woven with Passion', max_length=255)),
                ('content', models.TextField(help_text='This appears as the italic description')),
                ('image_1', models.ImageField(upload_to='brand_story/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='brand_story/')),
                ('experience_years', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BrandFeature',
        ),
        migrations.DeleteModel(
            name='BrandStory',
        ),
        migrations.RenameField(
            model_name='heroslide',
            old_name='title',
            new_name='title_italic',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_main',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='hero_slides/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
