# Generated by Django 5.2.11 on 2026-02-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_announcement_brandstorysettings_delete_brandfeature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='title_italic',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='title_main',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='link_url',
            field=models.CharField(default='/category/all', help_text='The internal route the user goes to (e.g., /category/sarees or /category/all)', max_length=255),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Recommended Ratios: 21:8 for Desktop (e.g., 2100x800px) and 3:2 for Mobile (e.g., 1200x800px). Ensure titles are part of the image.', upload_to='hero_slides/'),
        ),
    ]
