# Generated by Django 5.2.11 on 2026-02-15 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_heroslide_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandstorysettings',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='brandstorysettings',
            name='image_2',
        ),
        migrations.AlterField(
            model_name='brandstorysettings',
            name='content',
            field=models.TextField(default='Every design is a tribute to the timeless beauty of the Indian woman.', help_text='Main description text'),
        ),
        migrations.CreateModel(
            name='BrandStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand_story/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.brandstorysettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
