# Generated by Django 5.2.11 on 2026-02-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_brandstorysettings_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandstorysettings',
            name='content',
            field=models.TextField(default='Every design is a tribute to the timeless beauty of the Indian woman.', help_text='The main description (rendered in italics)'),
        ),
        migrations.AlterField(
            model_name='brandstorysettings',
            name='heading',
            field=models.CharField(default='Traditional Elegance | Effortlessly Styled', help_text="Line 1 and Line 2 are separated by '|'. Line 2 will automatically be Pink and Italic.", max_length=255),
        ),
        migrations.AlterField(
            model_name='brandstorysettings',
            name='tagline',
            field=models.CharField(default='The Art of Draping', max_length=100),
        ),
    ]
