# Generated by Django 5.2.11 on 2026-03-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0001_initial'),
        ('watch_and_buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Product'), ('WATCH_BUY', 'Watch & Buy')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='watch_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch_and_buy.watchandbuyvideo'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
