# Generated by Django 5.2.11 on 2026-03-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
