# Generated by Django 5.2.11 on 2026-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_tracking_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_note',
            field=models.TextField(blank=True, help_text='Enter Tracking ID and instructions (e.g. ID: 12345. Track at dtdc.in)', null=True),
        ),
    ]
